#cloud-config

apt_update:  true
apt_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - docker-engine

apt_sources:
  - keyid: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    source: deb https://apt.dockerproject.org/repo ubuntu-xenial main

groups:
  - openvpn
  - dnsmasq

users:
  - name: openvpn
    primary-group: openvpn
    homedir: /etc/openvpn
    no-create-home: true
    shell: /bin/false
  - name: dnsmasq
    primary-group: dnsmasq
    system: true
    no-create-home: true
    shell: /bin/false

runcmd:
  - mkdir -p /etc/openvpn
  - chown -R openvpn:openvpn /etc/openvpn

  - systemctl daemon-reload
  - systemctl enable openvpn.service
  - systemctl start --no-block openvpn.service
  - systemctl enable dnsmasq.service
  - systemctl start --no-block dnsmasq.service

write_files:
  - path: /etc/openvpn/openvpn.conf
    encoding: b64
    content: ${openvpn_conf}
    permissions: "0600"

  - path: /etc/openvpn/ca.pem
    encoding: b64
    content: ${openvpn_ca_pem}
    permissions: "0600"

  - path: /etc/openvpn/server.pem
    encoding: b64
    content: ${openvpn_server_pem}
    permissions: "0600"

  - path: /etc/openvpn/server.key
    encoding: b64
    content: ${openvpn_server_key}
    permissions: "0600"

  - path: /etc/openvpn/exec-fw.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -ex
      rule="POSTROUTING -o eth0 -s ${openvpn_ip_addr}/${openvpn_ip_mask} -j MASQUERADE"
      iptables -t nat -C $rule || iptables -t nat -I $rule

  - path: /etc/openvpn/exec-gen-dh.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -ex
      if [ ! -f /etc/openvpn/dh2048.pem ] ; then
        openssl dhparam -out /etc/openvpn/dh2048.pem 2048
        chown openvpn:openvpn /etc/openvpn/dh2048.pem
        chmod 0600 /etc/openvpn/dh2048.pem
      fi

  - path: /etc/openvpn/exec-gen-ta.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -ex
      if [ ! -f /etc/openvpn/ta.key ] ; then
        docker run --rm \
          -v /etc/openvpn:/etc/openvpn \
          kylemanna/openvpn \
          /usr/sbin/openvpn --genkey --secret /etc/openvpn/ta.key
        chown openvpn:openvpn /etc/openvpn/ta.key
        chmod 0600 /etc/openvpn/ta.key
      fi

  - path: /etc/openvpn/exec-sysctl.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -ex
      sysctl -w \
        net.ipv4.ip_forward=1 \
        net.ipv4.conf.all.accept_redirects=0 \
        net.ipv4.conf.all.send_redirects=0

  - path: /etc/systemd/system/openvpn.service
    content: |
      [Unit]
      Description=OpenVPN Server
      After=docker.service network-online.target
      Requires=docker.service network-online.target
      [Service]
      Restart=always
      RestartSec=10
      TimeoutStartSec=5m
      ExecStartPre=/etc/openvpn/exec-gen-ta.sh
      ExecStartPre=/etc/openvpn/exec-gen-dh.sh
      ExecStartPre=/etc/openvpn/exec-fw.sh
      ExecStartPre=/etc/openvpn/exec-sysctl.sh
      ExecStartPre=/sbin/modprobe tun
      ExecStart=/usr/bin/docker run \
        --rm \
        --name openvpn \
        --net host \
        --cap-add NET_ADMIN \
        -v /etc/openvpn:/etc/openvpn:ro \
        -v /etc/passwd:/etc/passwd:ro \
        -v /etc/group:/etc/group:ro \
        -v /dev/net/tun:/dev/net/tun \
        -w /etc/openvpn \
        ${openvpn_image} \
        /usr/sbin/openvpn --config /etc/openvpn/openvpn.conf
      ExecReload=/usr/bin/docker kill -s HUP openvpn
      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/dnsmasq.service
    content: |
      [Unit]
      Description=Dnsmasq Server
      After=docker.service network-online.target openvpn.service
      Requires=docker.service network-online.target openvpn.service
      [Service]
      Restart=always
      RestartSec=10
      ExecStart=/usr/bin/docker run \
        --rm \
        --name dnsmasq \
        --net host \
        --cap-add NET_ADMIN \
        -v /etc/passwd:/etc/passwd:ro \
        -v /etc/group:/etc/group:ro \
        ${dnsmasq_image} \
        -a ${openvpn_ip_addr} -d -z -u dnsmasq -g dnsmasq
      ExecStop=/usr/bin/docker kill -s TERM dnsmasq
      [Install]
      WantedBy=multi-user.target

